// Hot Spot contract reference data from Hot Spots: Draconis Reach
// All hot spots with their opposing contract pairs and accurate monthly track schedules.

export type ScheduleType = "fixed" | "roll-based" | "special";

export interface ScheduledTrack {
  trackType: string; // matches GENERAL_TRACKS names: "Recon", "Strike", etc.
  attackerSide: "A" | "B" | "winner" | "loser" | "conditional";
  note?: string;
}

export interface MonthSchedule {
  month: number;
  tracks: ScheduledTrack[]; // empty array = no tracks this month
  note?: string;
  isConditional?: boolean;
}

export interface RollTableEntry {
  roll: number;
  trackType: string | null; // null = no track on this result
  attackerSide: "A" | "B" | null;
}

export interface ContractTemplate {
  contractNumber: string;
  name: string;
  employer: string;
  contractType: string;
  terrain: string;
  planet: string;
  faction: string;
  durationMonths: number;
  basePayPct: number;
  basePayStep: number;
  supportType: string;
  supportPct: number;
  supportStep: number;
  transportPct: number;
  transportStep: number;
  salvageRightsPct: number;
  salvageStep: number;
  commandRights: string;
  commandStep: number;
  commandNonNegotiable: boolean;
  intensity: string;
  trackSequence: string;
  victoryCondition: string;
  specialRules: string;
  purchaseOptions: string;
  side: "A" | "B";
  optional?: boolean;
}

export interface HotSpotData {
  name: string;
  planet: string;
  primaryTerrain: string;
  faction: string;
  recommendedFor: "NEW_PLAYERS" | "EXPERIENCED" | "VETERAN_CAPSTONE";
  contracts: ContractTemplate[];
  scheduleType: ScheduleType;
  /** Month-by-month track schedule for fixed hot spots */
  monthlySchedule?: MonthSchedule[];
  /** Track selection table for roll-based hot spots */
  rollTable?: RollTableEntry[];
  /** How many dice to roll per month for roll-based hot spots */
  rollsPerMonth?: number;
  /** Victory condition notes for roll-based hot spots */
  rollVictoryNote?: string;
}

export const HOT_SPOTS_DATA: HotSpotData[] = [
  {
    name: "Achernar",
    planet: "Achernar",
    primaryTerrain: "Wooded",
    faction: "Capellan Confederation",
    recommendedFor: "EXPERIENCED",
    scheduleType: "fixed",
    monthlySchedule: [
      { month: 1, tracks: [], note: "No tracks — travel and preparation" },
      { month: 2, tracks: [{ trackType: "Meeting Engagement", attackerSide: "A" }] },
      {
        month: 3, isConditional: true,
        tracks: [{ trackType: "Pursuit", attackerSide: "A", note: "If A won Month 2" }, { trackType: "Recon", attackerSide: "B", note: "If B won Month 2" }],
        note: "Pursuit (A Attacker) if Tybalt won Track 1; Recon (B Attacker) if Home Guard won",
      },
      {
        month: 4, isConditional: true,
        tracks: [{ trackType: "Strike", attackerSide: "A", note: "A won M2+M3" }, { trackType: "Meeting Engagement", attackerSide: "B", note: "B won M2, A won M3" }, { trackType: "Breakthrough", attackerSide: "A", note: "A won M2, B won M3" }, { trackType: "Defend", attackerSide: "A", note: "B won M2+M3" }],
        note: "Track depends on winners of first two tracks (see table in book)",
      },
      { month: 5, tracks: [{ trackType: "Breakthrough", attackerSide: "A" }] },
      { month: 6, tracks: [{ trackType: "Retreat", attackerSide: "B", note: "Tybalt (A) is Defender" }] },
    ],
    contracts: [
      {
        contractNumber: "181999A",
        name: "Objective Raid",
        employer: "Loren Hansen, Duke of Tybalt",
        contractType: "EXPEDITION",
        terrain: "Wooded",
        planet: "Achernar",
        faction: "Capellan Confederation",
        durationMonths: 6,
        basePayPct: 110, basePayStep: 8,
        supportType: "STRAIGHT", supportPct: 80, supportStep: 6,
        transportPct: 100, transportStep: 9,
        salvageRightsPct: 40, salvageStep: 7,
        commandRights: "INDEPENDENT", commandStep: 11,
        commandNonNegotiable: false,
        intensity: "5 tracks over 6 months",
        trackSequence: "M1: No tracks. M2: Meeting Engagement (A Attacker). M3: Conditional on M2 winner — Pursuit (A) or Recon (B). M4: Conditional on M2+M3 winners. M5: Breakthrough (A). M6: Retreat (A Defender).",
        victoryCondition: "Tybalt wins if at least one defector J. Edgar Hover Tank survives all tracks, OR wins both Strike and Retreat if all vehicles destroyed.",
        specialRules: "2 J. Edgar Hover Tanks join Tybalt in M4+. Temp hire: Nondy Pritchard in Cougar Prime (1,485 BV / 31 PV, 100 SP/track).",
        purchaseOptions: "Roll 2D6 after each track: 7+ = 1 Mech; 10+ = 2 Mechs. Achernar BattleMech Recovery Table.",
        side: "A",
      },
      {
        contractNumber: "181999B",
        name: "Planetary Defense",
        employer: "Achernar Home Guard",
        contractType: "RETAINER",
        terrain: "Wooded",
        planet: "Achernar",
        faction: "Capellan Confederation",
        durationMonths: 6,
        basePayPct: 100, basePayStep: 7,
        supportType: "BATTLE", supportPct: 20, supportStep: 10,
        transportPct: 0, transportStep: 5,
        salvageRightsPct: 50, salvageStep: 8,
        commandRights: "LIAISON", commandStep: 8,
        commandNonNegotiable: false,
        intensity: "5 tracks over 6 months",
        trackSequence: "Opposing contract to 181999A. Same Achernar Timeline applies.",
        victoryCondition: "Home Guard wins if Tybalt does not meet their victory conditions, or destroys 5+ battlefield support units granted to Tybalt.",
        specialRules: "Command Complications Table rolled each track. Temp hire: Nondy Pritchard in Cougar Prime.",
        purchaseOptions: "Same as 181999A — Achernar BattleMech Recovery Table.",
        side: "B",
      },
    ],
  },

  {
    name: "Alta Vista",
    planet: "Alta Vista",
    primaryTerrain: "Urban",
    faction: "Clan Sea Fox Enclave",
    recommendedFor: "NEW_PLAYERS",
    scheduleType: "fixed",
    monthlySchedule: [
      { month: 1, tracks: [{ trackType: "Meeting Engagement", attackerSide: "B", note: "Trial 1 — Warehouse 1" }] },
      { month: 2, tracks: [{ trackType: "Meeting Engagement", attackerSide: "B", note: "Trial 2 — Warehouse 2 (if Ravens haven't won yet)" }], isConditional: true, note: "If Ravens win Trial 1 and find worthless cargo, Extraction track may follow instead" },
      { month: 3, tracks: [{ trackType: "Meeting Engagement", attackerSide: "B", note: "Trial 3 — Warehouse 3 (if contract still active)" }], isConditional: true, note: "If Ravens win and choose Extraction, play that instead. Contract ends when Ravens find the cargo or all 3 trials are done." },
    ],
    contracts: [
      {
        contractNumber: "565634A",
        name: "Holding Down the Fort",
        employer: "Merchant Colonel Escobar of Clan Sea Fox",
        contractType: "GARRISON",
        terrain: "Urban (Light)",
        planet: "Alta Vista",
        faction: "Clan Sea Fox Enclave",
        durationMonths: 3,
        basePayPct: 100, basePayStep: 7,
        supportType: "NONE", supportPct: 0, supportStep: 1,
        transportPct: 100, transportStep: 5,
        salvageRightsPct: 50, salvageStep: 8,
        commandRights: "LIAISON", commandStep: 8,
        commandNonNegotiable: true,
        intensity: "1–4 Meeting Engagement tracks, one per month",
        trackSequence: "One trial per month (Meeting Engagement, B Attacker). Up to 3 warehouse trials. If Ravens win a trial and cargo is worthless, they may choose one Extraction track. Contract ends after all trials or Extraction.",
        victoryCondition: "Escobar wins if they complete half or more of Meeting Engagement tracks and do not break contract.",
        specialRules: "Escobar bonus: may purchase one Mech of same class as any lost at half price. Command Complications rolled by Escobar player.",
        purchaseOptions: "Roll once on Sea Fox Purchase Options Table each month.",
        side: "A",
      },
      {
        contractNumber: "565634B",
        name: "Militant Archaeology",
        employer: "Alliance Industries Diversified",
        contractType: "RAID",
        terrain: "Urban (Light)",
        planet: "Alta Vista",
        faction: "Clan Sea Fox Enclave",
        durationMonths: 3,
        basePayPct: 100, basePayStep: 7,
        supportType: "NONE", supportPct: 0, supportStep: 1,
        transportPct: 100, transportStep: 9,
        salvageRightsPct: 100, salvageStep: 13,
        commandRights: "LIAISON", commandStep: 8,
        commandNonNegotiable: true,
        intensity: "1–4 tracks",
        trackSequence: "Opposing contract to 565634A. Ravens attack Escobar warehouses in Trial of Possession format, one per month.",
        victoryCondition: "Ravens win if they win the Extraction track after discovering the cargo is worthless.",
        specialRules: "Alliance Industries pays salvage value of any enemy units destroyed as a discount on purchases. Temp hires: Raven (War Crow Prime), Roland D'Isque.",
        purchaseOptions: "Alliance Defenders Limited table during contract.",
        side: "B",
      },
    ],
  },

  {
    name: "Dahar",
    planet: "Dahar IV",
    primaryTerrain: "Desert",
    faction: "Federated Suns",
    recommendedFor: "NEW_PLAYERS",
    scheduleType: "roll-based",
    rollsPerMonth: 2,
    rollVictoryNote: "Win by completing 2 tracks in a row, or most completed tracks after 3 months.",
    rollTable: [
      { roll: 1, trackType: "Recon",              attackerSide: "B" },
      { roll: 2, trackType: "Flank",              attackerSide: "B" },
      { roll: 3, trackType: "Strike",             attackerSide: "B" },
      { roll: 4, trackType: "Meeting Engagement", attackerSide: "A" },
      { roll: 5, trackType: "Assault",            attackerSide: "A" },
      { roll: 6, trackType: "Retreat",            attackerSide: "A" },
    ],
    contracts: [
      {
        contractNumber: "105112A",
        name: "Dahar Garrison",
        employer: "Duke Romy Sandoval-Dobson",
        contractType: "GARRISON",
        terrain: "Desert",
        planet: "Dahar IV",
        faction: "Federated Suns",
        durationMonths: 3,
        basePayPct: 100, basePayStep: 7,
        supportType: "BATTLE", supportPct: 30, supportStep: 11,
        transportPct: 50, transportStep: 7,
        salvageRightsPct: 25, salvageStep: 5,
        commandRights: "LIAISON", commandStep: 8,
        commandNonNegotiable: true,
        intensity: "1–6 tracks (roll 1D6 twice per month)",
        trackSequence: "Each month: roll 1D6 twice. Each result maps to a track type (see table). Duplicates = no track for that roll. Tracks 1–3 have Raid as Attacker; tracks 4–6 have Garrison as Attacker.",
        victoryCondition: "2 consecutive completed tracks wins. Otherwise most tracks completed after 3 months.",
        specialRules: "Repurposed Equipment: per scale, each side adds one IndustrialMech MOD from Dahar table. Re-rolled each mission, does not count toward scale limits.",
        purchaseOptions: "Roll 2D6 each month: 7+ = 1 Mech; 11+ = 2. Dahar IndustrialMech table available.",
        side: "A",
      },
      {
        contractNumber: "105112B",
        name: "Dahar Raid",
        employer: "Felix Kurita",
        contractType: "RAID",
        terrain: "Desert",
        planet: "Dahar IV",
        faction: "Federated Suns",
        durationMonths: 3,
        basePayPct: 80, basePayStep: 5,
        supportType: "BATTLE", supportPct: 20, supportStep: 10,
        transportPct: 100, transportStep: 9,
        salvageRightsPct: 50, salvageStep: 8,
        commandRights: "LIAISON", commandStep: 8,
        commandNonNegotiable: false,
        intensity: "1–6 tracks (same roll mechanism as Dahar Garrison)",
        trackSequence: "Opposing contract to 105112A. Same roll-based track system. Each player rolls separately for complications.",
        victoryCondition: "Same as 105112A.",
        specialRules: "Same repurposed equipment rules. Command Complications: 1–3 No Complication, 4 Sandstorm, 5 Heatwave, 6 Mine Complex, 7 Gibberish Orders, 8 Roll twice.",
        purchaseOptions: "Same tables as 105112A.",
        side: "B",
      },
    ],
  },

  {
    name: "Le Blanc",
    planet: "Le Blanc",
    primaryTerrain: "Wooded/Urban",
    faction: "Draconis Combine",
    recommendedFor: "NEW_PLAYERS",
    scheduleType: "fixed",
    monthlySchedule: [
      { month: 1, tracks: [], note: "No tracks — Fed Suns occupy positions and begin garrison duty. Both receive base pay." },
      { month: 2, tracks: [], note: "No tracks — DC smuggled on-planet, gathers intelligence. Both receive base pay." },
      { month: 3, tracks: [{ trackType: "Objective Raid", attackerSide: "B", note: "DC initiates raid on Fed Suns supply depots" }] },
      {
        month: 4, isConditional: true,
        tracks: [
          { trackType: "Strike", attackerSide: "B", note: "If DC won Month 3" },
          { trackType: "Retreat", attackerSide: "B", note: "If Fed Suns won Month 3 — DC forced to flee" },
        ],
        note: "Strike (B Attacker) if DC won Month 3; Retreat (B Defender) if Fed Suns won Month 3",
      },
    ],
    contracts: [
      {
        contractNumber: "233445A",
        name: "Operation Sundown",
        employer: "Duke Erik Sandoval-Groell, Federated Suns",
        contractType: "RAID",
        terrain: "Wooded/Urban",
        planet: "Le Blanc",
        faction: "Draconis Combine",
        durationMonths: 4,
        basePayPct: 100, basePayStep: 7,
        supportType: "STRAIGHT", supportPct: 80, supportStep: 6,
        transportPct: 75, transportStep: 8,
        salvageRightsPct: 50, salvageStep: 8,
        commandRights: "INDEPENDENT", commandStep: 11,
        commandNonNegotiable: false,
        intensity: "1–2 tracks over 4 months",
        trackSequence: "M1: No tracks (travel/garrison). M2: No tracks (DC planning). M3: Objective Raid (B Attacker). M4: Strike or Retreat (B) conditional on M3 result.",
        victoryCondition: "Fed Suns win if DC does not complete their primary objective or breaks contract.",
        specialRules: "Urban terrain rules. Command Complications each track.",
        purchaseOptions: "Roll 2D6 each month: 7+ = 1 Mech; 11+ = 2. Federated Suns Purchase Options Table.",
        side: "A",
      },
      {
        contractNumber: "233445B",
        name: "Le Blanc Garrison",
        employer: "Tai-sa Yamoto, Draconis Combine",
        contractType: "GARRISON",
        terrain: "Wooded/Urban",
        planet: "Le Blanc",
        faction: "Draconis Combine",
        durationMonths: 4,
        basePayPct: 90, basePayStep: 6,
        supportType: "STRAIGHT", supportPct: 100, supportStep: 7,
        transportPct: 50, transportStep: 7,
        salvageRightsPct: 30, salvageStep: 6,
        commandRights: "HOUSE", commandStep: 7,
        commandNonNegotiable: false,
        intensity: "1–2 tracks over 4 months",
        trackSequence: "Opposing contract to 233445A. Same Le Blanc timeline.",
        victoryCondition: "DC wins if they complete their primary objective across the two action months.",
        specialRules: "DC reinforcements available at certain milestones.",
        purchaseOptions: "Draconis Combine Purchase Options Table.",
        side: "B",
      },
    ],
  },

  {
    name: "Lucerne",
    planet: "Lucerne",
    primaryTerrain: "Wooded",
    faction: "Raven Alliance",
    recommendedFor: "EXPERIENCED",
    scheduleType: "roll-based",
    rollsPerMonth: 2,
    rollVictoryNote: "Contract ends after 6 total tracks. Track 6 is always Bio-Gen Raid. Most tracks completed wins; if tied, no victor.",
    rollTable: [
      { roll: 1, trackType: "Recon",          attackerSide: "B" },
      { roll: 2, trackType: "Breakthrough",   attackerSide: "B" },
      { roll: 3, trackType: "Objective Raid", attackerSide: "B" },
      { roll: 4, trackType: "Pushback",       attackerSide: "A" },
      { roll: 5, trackType: "Pursuit",        attackerSide: "A" },
      { roll: 6, trackType: "Assault",        attackerSide: "B" },
    ],
    contracts: [
      {
        contractNumber: "477821A",
        name: "Bio-Gen Retainer",
        employer: "Bio-Gen Corporation",
        contractType: "RETAINER",
        terrain: "Wooded",
        planet: "Lucerne",
        faction: "Raven Alliance",
        durationMonths: 4,
        basePayPct: 110, basePayStep: 8,
        supportType: "STRAIGHT", supportPct: 100, supportStep: 7,
        transportPct: 100, transportStep: 9,
        salvageRightsPct: 30, salvageStep: 6,
        commandRights: "LIAISON", commandStep: 8,
        commandNonNegotiable: false,
        intensity: "6 tracks total (roll 2D6 per month from table)",
        trackSequence: "Each month roll two 1D6s for tracks. Duplicates = no track. Roll 5 generates 2 Pursuit tracks; Roll 6 generates 2 Assault tracks. 6th track is always Bio-Gen Raid finale regardless of rolls.",
        victoryCondition: "Bio-Gen wins if they protect the research facility through all tracks. Most completed tracks after 6 total wins.",
        specialRules: "Eclipse covert operations special rules apply for one track.",
        purchaseOptions: "Roll 2D6 each month: 7+ = 1 Mech; 11+ = 2. Raven Alliance table.",
        side: "A",
      },
      {
        contractNumber: "477821B",
        name: "Eclipse Expeditions Special Operations",
        employer: "Eclipse Expeditions",
        contractType: "RAID",
        terrain: "Wooded",
        planet: "Lucerne",
        faction: "Raven Alliance",
        durationMonths: 4,
        basePayPct: 100, basePayStep: 7,
        supportType: "BATTLE", supportPct: 20, supportStep: 10,
        transportPct: 100, transportStep: 9,
        salvageRightsPct: 60, salvageStep: 9,
        commandRights: "INDEPENDENT", commandStep: 11,
        commandNonNegotiable: false,
        intensity: "6 tracks total (same roll system as Bio-Gen Retainer)",
        trackSequence: "Opposing contract to 477821A. Same Lucerne roll system.",
        victoryCondition: "Eclipse wins if they successfully extract the research data objective.",
        specialRules: "Special covert operations rules apply in one track. Bio-Gen Raid contract also available as alternative.",
        purchaseOptions: "Mercenary/Pirate Purchase Options Table.",
        side: "B",
      },
    ],
  },

  {
    name: "Melcher",
    planet: "Melcher",
    primaryTerrain: "Agricultural/Plains",
    faction: "Draconis Combine",
    recommendedFor: "EXPERIENCED",
    scheduleType: "fixed",
    monthlySchedule: [
      { month: 1, tracks: [], note: "No tracks — Border Collies acclimatize to garrison. Earwigs travel to system." },
      {
        month: 2, tracks: [
          { trackType: "Objective Raid", attackerSide: "A", note: "Track 1: Oxen Intercept — Earwigs escort CattleMasters to experimental fields. SIMULTANEOUS with Track 2." },
          { trackType: "Objective Raid", attackerSide: "A", note: "Track 2: Genetics lab raid — Earwigs escort scientists to Thousand Oaks Ranch. SIMULTANEOUS with Track 1." },
        ],
        note: "Both tracks occur simultaneously in Month 2. Contract requires Scale 2; force split into two Scale 1 groups.",
      },
      { month: 3, tracks: [], note: "No tracks — travel/extraction." },
    ],
    contracts: [
      {
        contractNumber: "867530A",
        name: "Cattle Rustling",
        employer: "Melcher Food Corporation (House Earwig)",
        contractType: "RETAINER",
        terrain: "Agricultural/Plains",
        planet: "Melcher",
        faction: "Draconis Combine",
        durationMonths: 3,
        basePayPct: 120, basePayStep: 9,
        supportType: "NONE", supportPct: 0, supportStep: 1,
        transportPct: 100, transportStep: 9,
        salvageRightsPct: 0, salvageStep: 1,
        commandRights: "INDEPENDENT", commandStep: 11,
        commandNonNegotiable: false,
        intensity: "2 tracks simultaneously in Month 2",
        trackSequence: "M1: No tracks (travel). M2: Two Objective Raids played simultaneously — Earwigs split at Scale 1 each. Track 1 = Oxen Intercept. Track 2 = Thousand Oaks genetics lab. M3: No tracks.",
        victoryCondition: "Earwigs win if both recovery teams, data, samples, and animals are returned to New Valencia.",
        specialRules: "Must take at Scale 2. CattleMasters used for herding. 100% battle loss compensation after contract. Force split into two Scale 1 groups for simultaneous tracks.",
        purchaseOptions: "Roll 2D6 after each track: 9+ = 1 Mech; 12+ = 2. Sea Fox merchant check each month.",
        side: "A",
      },
      {
        contractNumber: "867530B",
        name: "Thousand Oaks Garrison",
        employer: "DCMS District Command / Surinami Processing",
        contractType: "GARRISON",
        terrain: "Agricultural/Plains",
        planet: "Melcher",
        faction: "Draconis Combine",
        durationMonths: 3,
        basePayPct: 100, basePayStep: 7,
        supportType: "STRAIGHT", supportPct: 100, supportStep: 7,
        transportPct: 50, transportStep: 7,
        salvageRightsPct: 20, salvageStep: 4,
        commandRights: "HOUSE", commandStep: 7,
        commandNonNegotiable: false,
        intensity: "2 tracks in Month 2",
        trackSequence: "Opposing contract to 867530A. Border Collies defend Thousand Oaks Ranch and experimental fields simultaneously.",
        victoryCondition: "Garrison wins if they prevent the Earwigs from recovering the genetic assets and lab data.",
        specialRules: "Draconis Combine reinforcements available. Oxen Intercept special track rules.",
        purchaseOptions: "Same tables as 867530A.",
        side: "B",
      },
    ],
  },

  {
    name: "New Ivaarsen",
    planet: "New Ivaarsen",
    primaryTerrain: "Wooded/Hills",
    faction: "Federated Suns",
    recommendedFor: "EXPERIENCED",
    scheduleType: "fixed",
    monthlySchedule: [
      { month: 1, tracks: [{ trackType: "Strike", attackerSide: "A", note: "Stephensons attack ISF positions" }] },
      { month: 2, tracks: [{ trackType: "Meeting Engagement", attackerSide: "A" }] },
      { month: 3, tracks: [{ trackType: "Assault", attackerSide: "B", note: "ISF pushes back" }] },
    ],
    contracts: [
      {
        contractNumber: "198234A",
        name: "Asset Recovery",
        employer: "New Ivaarsen Chasseurs (Stephensons)",
        contractType: "EXPEDITION",
        terrain: "Wooded/Hills",
        planet: "New Ivaarsen",
        faction: "Federated Suns",
        durationMonths: 3,
        basePayPct: 100, basePayStep: 7,
        supportType: "BATTLE", supportPct: 30, supportStep: 11,
        transportPct: 75, transportStep: 8,
        salvageRightsPct: 50, salvageStep: 8,
        commandRights: "INDEPENDENT", commandStep: 11,
        commandNonNegotiable: false,
        intensity: "3 tracks, one per month",
        trackSequence: "M1: Strike (A Attacker). M2: Meeting Engagement (A Attacker). M3: Assault (B/ISF Attacker).",
        victoryCondition: "Stephensons win if they retrieve at least two of the three missing asset caches.",
        specialRules: "Building destruction reduces Mech availability roll. ISF player applies −2 to purchase rolls.",
        purchaseOptions: "Roll 2D6 after each track (modified by building hexes destroyed). 9+ = 1 Mech; 12+ = 2. Ryuken-ni Support table.",
        side: "A",
      },
      {
        contractNumber: "198234B",
        name: "Guerrilla Suppression",
        employer: "Draconis Combine Occupation Force (ISF)",
        contractType: "GARRISON",
        terrain: "Wooded/Hills",
        planet: "New Ivaarsen",
        faction: "Federated Suns",
        durationMonths: 3,
        basePayPct: 80, basePayStep: 5,
        supportType: "STRAIGHT", supportPct: 80, supportStep: 6,
        transportPct: 50, transportStep: 7,
        salvageRightsPct: 30, salvageStep: 6,
        commandRights: "HOUSE", commandStep: 7,
        commandNonNegotiable: false,
        intensity: "3 tracks, one per month",
        trackSequence: "Opposing contract to 198234A. M1: Strike (A). M2: Meeting Engagement (A). M3: Assault (B/ISF).",
        victoryCondition: "ISF wins if they prevent Stephensons from recovering their objectives and destroy or drive off enemy.",
        specialRules: "Local resistance fighters may join Stephensons in certain tracks.",
        purchaseOptions: "Same roll system as 198234A.",
        side: "B",
      },
    ],
  },

  {
    name: "Pascagoula",
    planet: "Pascagoula",
    primaryTerrain: "Urban/Wetlands",
    faction: "Federated Suns",
    recommendedFor: "NEW_PLAYERS",
    scheduleType: "fixed",
    monthlySchedule: [
      { month: 1, tracks: [], note: "No tracks — travel and preparation." },
      {
        month: 2, isConditional: true,
        tracks: [
          { trackType: "Objective Raid", attackerSide: "B", note: "Track 1: Ranger Raiders attack gem convoy. Jewel Thieves play Fifth Ghost escorts as Defenders." },
          { trackType: "Pursuit", attackerSide: "conditional", note: "Track 2: Winner of Track 1 is Attacker. No repairs or reloads between tracks — damage carries over." },
        ],
        note: "Both tracks play in Month 2 back-to-back. No repair between them. Attacker in Track 2 determined by Track 1 winner.",
      },
      { month: 3, tracks: [], note: "No tracks — Pirates escape, Planetary Militia regroups." },
    ],
    contracts: [
      {
        contractNumber: "087523A",
        name: "Family Jewels",
        employer: "House Davion noble family",
        contractType: "RAID",
        terrain: "Urban/Wetlands",
        planet: "Pascagoula",
        faction: "Federated Suns",
        durationMonths: 3,
        basePayPct: 100, basePayStep: 7,
        supportType: "STRAIGHT", supportPct: 80, supportStep: 6,
        transportPct: 100, transportStep: 9,
        salvageRightsPct: 50, salvageStep: 8,
        commandRights: "INDEPENDENT", commandStep: 11,
        commandNonNegotiable: false,
        intensity: "2 tracks in Month 2",
        trackSequence: "M1: No tracks. M2: Two back-to-back tracks with no repair between — Objective Raid (B Attacker) then Pursuit (winner determines A/D). M3: No tracks.",
        victoryCondition: "Jewel Thieves win if the oyabun successfully extracts the gem train assets.",
        specialRules: "Jewel Thieves play Fifth Ghost escorts (not their own units) as Defenders in Track 1. Damage and ammo carry over to Track 2.",
        purchaseOptions: "One purchase from Draconis Combine faction table each month.",
        side: "A",
      },
      {
        contractNumber: "087523B",
        name: "The Great Ruby Robbery",
        employer: "Pascagoula Planetary Militia",
        contractType: "GARRISON",
        terrain: "Urban/Wetlands",
        planet: "Pascagoula",
        faction: "Federated Suns",
        durationMonths: 3,
        basePayPct: 90, basePayStep: 6,
        supportType: "STRAIGHT", supportPct: 100, supportStep: 7,
        transportPct: 25, transportStep: 6,
        salvageRightsPct: 30, salvageStep: 6,
        commandRights: "LIAISON", commandStep: 8,
        commandNonNegotiable: false,
        intensity: "2 tracks in Month 2",
        trackSequence: "Opposing contract to 087523A. Same Pascagoula timeline.",
        victoryCondition: "Ranger Raiders win if they prevent the gem extraction.",
        specialRules: "Wetlands terrain. Civilian evacuee rules in Track 1.",
        purchaseOptions: "One purchase from Federated Suns faction table each month. No purchases between the two Month 2 tracks.",
        side: "B",
      },
    ],
  },

  {
    name: "Protection",
    planet: "Protection",
    primaryTerrain: "Desert/Arid",
    faction: "Federated Suns",
    recommendedFor: "EXPERIENCED",
    scheduleType: "fixed",
    monthlySchedule: [
      { month: 1, tracks: [], note: "No tracks — both forces square away in garrison. Platinum Sands retainer sorties grow aggressive but avoid outright hostilities. Both receive base pay." },
      { month: 2, tracks: [{ trackType: "Recon", attackerSide: "A", note: "Platinum Sands initiates first hostilities" }] },
      { month: 3, tracks: [{ trackType: "Meeting Engagement", attackerSide: "winner", note: "Winner of Month 2 Recon is Attacker" }], isConditional: true },
      {
        month: 4, isConditional: true,
        tracks: [
          { trackType: "Assault",          attackerSide: "A", note: "If A won both previous tracks" },
          { trackType: "Pushback",         attackerSide: "B", note: "If B won both previous tracks" },
          { trackType: "Flank",            attackerSide: "conditional", note: "If split (1–1) — roll-off determines Attacker/Defender" },
        ],
        note: "Assault (A) if Platinum Sands won both; Pushback (B) if Kanagawa won both; Flank (roll-off) if split 1–1",
      },
      { month: 5, tracks: [{ trackType: "Pursuit", attackerSide: "A", note: "Platinum Sands chases Governor Hale's escape vehicle. Special rules: capture vehicle rather than destroy." }] },
    ],
    contracts: [
      {
        contractNumber: "138910A",
        name: "Platinum Sands Supplemental Security Agreement",
        employer: "Platinum Sands Mining Consortium",
        contractType: "RETAINER",
        terrain: "Desert/Arid",
        planet: "Protection",
        faction: "Federated Suns",
        durationMonths: 5,
        basePayPct: 110, basePayStep: 8,
        supportType: "STRAIGHT", supportPct: 80, supportStep: 6,
        transportPct: 100, transportStep: 9,
        salvageRightsPct: 40, salvageStep: 7,
        commandRights: "INDEPENDENT", commandStep: 11,
        commandNonNegotiable: false,
        intensity: "4 tracks over 5 months (escalating)",
        trackSequence: "M1: No tracks. M2: Recon (A). M3: Meeting Engagement (winner of M2). M4: Conditional Assault/Pushback/Flank. M5: Pursuit (A — capture Governor Hale).",
        victoryCondition: "Platinum Sands wins if they control the platinum mining district at contract end.",
        specialRules: "Desert heat rules. M5 special rule: capture (not destroy) Kanagawa Mobile HQ carrying Governor Hale.",
        purchaseOptions: "Roll 2D6 each month: 7+ = 1 Mech; 11+ = 2. Both Federated Suns and Draconis Combine tables available.",
        side: "A",
      },
      {
        contractNumber: "138910B",
        name: "Protection Garrison",
        employer: "Kanagawa Group / DCMS Garrison Command",
        contractType: "GARRISON",
        terrain: "Desert/Arid",
        planet: "Protection",
        faction: "Federated Suns",
        durationMonths: 5,
        basePayPct: 100, basePayStep: 7,
        supportType: "STRAIGHT", supportPct: 100, supportStep: 7,
        transportPct: 50, transportStep: 7,
        salvageRightsPct: 20, salvageStep: 4,
        commandRights: "HOUSE", commandStep: 7,
        commandNonNegotiable: false,
        intensity: "4 tracks over 5 months",
        trackSequence: "Opposing contract to 138910A. Same Protection timeline. Kanagawa defends mining district.",
        victoryCondition: "Kanagawa Group wins if they prevent Platinum Sands from securing the platinum mining district.",
        specialRules: "Desert heat rules. Governor Hale Mobile HQ asset in M5.",
        purchaseOptions: "Same tables as 138910A.",
        side: "B",
      },
    ],
  },

  {
    name: "Sun Prairie",
    planet: "Sun Prairie",
    primaryTerrain: "Plains/Agricultural",
    faction: "Draconis Combine",
    recommendedFor: "EXPERIENCED",
    scheduleType: "roll-based",
    rollsPerMonth: 2,
    rollVictoryNote: "Win by completing 2 consecutive tracks. Otherwise most completed tracks after 3 months wins.",
    rollTable: [
      { roll: 1, trackType: "Breakthrough",      attackerSide: "B" },
      { roll: 2, trackType: "Objective Raid",    attackerSide: "B" },
      { roll: 3, trackType: "Strike",            attackerSide: "B" },
      { roll: 4, trackType: "Recon",             attackerSide: "A" },
      { roll: 5, trackType: "Meeting Engagement",attackerSide: "A" },
      { roll: 6, trackType: null,                attackerSide: null },
    ],
    contracts: [
      {
        contractNumber: "334671A",
        name: "Sun Prairie Garrison",
        employer: "Federated Suns Draconis March Command",
        contractType: "GARRISON",
        terrain: "Plains/Agricultural",
        planet: "Sun Prairie",
        faction: "Draconis Combine",
        durationMonths: 3,
        basePayPct: 100, basePayStep: 7,
        supportType: "STRAIGHT", supportPct: 80, supportStep: 6,
        transportPct: 75, transportStep: 8,
        salvageRightsPct: 40, salvageStep: 7,
        commandRights: "LIAISON", commandStep: 8,
        commandNonNegotiable: false,
        intensity: "1–5 tracks (roll 1D6 twice per month, 6 = no track)",
        trackSequence: "Each month: roll 1D6 twice. 1=Breakthrough (B), 2=Objective Raid (B), 3=Strike (B), 4=Recon (A), 5=Meeting Engagement (A), 6=No track. Duplicates also = no track.",
        victoryCondition: "2 consecutive completed tracks wins outright. Otherwise most completed tracks after 3 months.",
        specialRules: "Plains terrain. Agricultural buildings are objectives.",
        purchaseOptions: "Roll 2D6 each month: 7+ = 1 Mech; 11+ = 2. Federated Suns table.",
        side: "A",
      },
      {
        contractNumber: "334671B",
        name: "Sun Prairie Raid",
        employer: "DCMS District Strike Command",
        contractType: "RAID",
        terrain: "Plains/Agricultural",
        planet: "Sun Prairie",
        faction: "Draconis Combine",
        durationMonths: 3,
        basePayPct: 90, basePayStep: 6,
        supportType: "BATTLE", supportPct: 20, supportStep: 10,
        transportPct: 100, transportStep: 9,
        salvageRightsPct: 50, salvageStep: 8,
        commandRights: "INDEPENDENT", commandStep: 11,
        commandNonNegotiable: false,
        intensity: "1–5 tracks (same roll system as Sun Prairie Garrison)",
        trackSequence: "Opposing contract to 334671A. Same Sun Prairie roll system.",
        victoryCondition: "Same as 334671A.",
        specialRules: "Draconis Combine special operations rules.",
        purchaseOptions: "Draconis Combine table.",
        side: "B",
      },
    ],
  },

  {
    name: "Tigress",
    planet: "Tigress",
    primaryTerrain: "Jungle/Tropical",
    faction: "Federated Suns / Draconis Combine Contested",
    recommendedFor: "EXPERIENCED",
    scheduleType: "fixed",
    monthlySchedule: [
      { month: 1, tracks: [], note: "No tracks — garrison duty and travel." },
      {
        month: 2, tracks: [
          { trackType: "Meeting Engagement", attackerSide: "B", note: "Track 1: Legion Trainers cadre training exercise. Roughriders play opposing force. Wooded terrain mapsheets." },
          { trackType: "Meeting Engagement", attackerSide: "B", note: "Track 2: Remaining forces. Damage and criticals carry over. Hills terrain mapsheets." },
        ],
        note: "Both tracks occur in Month 2. Damage and critical hits carry over from Track 1 to Track 2.",
      },
      { month: 3, tracks: [], note: "No tracks — garrison duty and travel." },
    ],
    contracts: [
      {
        contractNumber: "556834A",
        name: "Tigress Trainers",
        employer: "Lyran Commonwealth Military Mission",
        contractType: "RETAINER",
        terrain: "Jungle/Tropical",
        planet: "Tigress",
        faction: "Draconis Combine",
        durationMonths: 3,
        basePayPct: 110, basePayStep: 8,
        supportType: "STRAIGHT", supportPct: 100, supportStep: 7,
        transportPct: 100, transportStep: 9,
        salvageRightsPct: 30, salvageStep: 6,
        commandRights: "LIAISON", commandStep: 8,
        commandNonNegotiable: false,
        intensity: "2 tracks in Month 2",
        trackSequence: "M1: No tracks. M2: Two Meeting Engagements — Track 1 (Wooded maps), Track 2 (Hills maps, damage carries over from T1). M3: No tracks.",
        victoryCondition: "Legion Trainers win if they successfully complete training objectives and protect their trainees.",
        specialRules: "Cadre duty rules: trainee units join Legion Trainers in some tracks with reduced skills. Damage carries over between the two Month 2 tracks.",
        purchaseOptions: "Roll once on Sea Fox Random Purchase Table each month. Roll once on Laurel's Legion Random Allocation Table each month.",
        side: "A",
      },
      {
        contractNumber: "556834B",
        name: "Roughriders Reconnaissance",
        employer: "Hansen's Roughriders Intelligence Directorate",
        contractType: "EXPEDITION",
        terrain: "Jungle/Tropical",
        planet: "Tigress",
        faction: "Draconis Combine",
        durationMonths: 3,
        basePayPct: 100, basePayStep: 7,
        supportType: "BATTLE", supportPct: 20, supportStep: 10,
        transportPct: 100, transportStep: 9,
        salvageRightsPct: 50, salvageStep: 8,
        commandRights: "INDEPENDENT", commandStep: 11,
        commandNonNegotiable: false,
        intensity: "2 tracks in Month 2",
        trackSequence: "Opposing contract to 556834A. Same Tigress timeline.",
        victoryCondition: "Roughriders win if they successfully identify opposing forces and extract intelligence.",
        specialRules: "Jungle terrain heat management rules. Damage carries over between the two Month 2 tracks.",
        purchaseOptions: "Same tables as 556834A.",
        side: "B",
      },
    ],
  },

  {
    name: "Xhosa VII",
    planet: "Xhosa VII",
    primaryTerrain: "Tundra/Arctic",
    faction: "Draconis Combine",
    recommendedFor: "EXPERIENCED",
    scheduleType: "fixed",
    monthlySchedule: [
      { month: 1, tracks: [{ trackType: "Recon", attackerSide: "A", note: "Fed Suns reconnoiters new DC arrivals" }] },
      { month: 2, tracks: [{ trackType: "Breakthrough", attackerSide: "A", note: "Supply convoy breakthrough — 50%+ trucks must pass through to succeed" }] },
      {
        month: 3, isConditional: true,
        tracks: [
          { trackType: "Assault",  attackerSide: "A", note: "If Fed Suns won Month 2 (50%+ trucks got through)" },
          { trackType: "Pushback", attackerSide: "B", note: "If DC won Month 2" },
        ],
        note: "Assault (A Attacker) if Fed Suns won Month 2; Pushback (B Attacker) if DC won",
      },
    ],
    contracts: [
      {
        contractNumber: "712345A",
        name: "Operation Cold Relief",
        employer: "Federated Suns Relief Organization",
        contractType: "EXPEDITION",
        terrain: "Tundra/Arctic",
        planet: "Xhosa VII",
        faction: "Draconis Combine",
        durationMonths: 3,
        basePayPct: 100, basePayStep: 7,
        supportType: "STRAIGHT", supportPct: 80, supportStep: 6,
        transportPct: 100, transportStep: 9,
        salvageRightsPct: 40, salvageStep: 7,
        commandRights: "INDEPENDENT", commandStep: 11,
        commandNonNegotiable: false,
        intensity: "3 tracks, one per month",
        trackSequence: "M1: Recon (A). M2: Breakthrough (A — supply convoy). M3: Assault (A) if convoy succeeded, Pushback (B) if DC won.",
        victoryCondition: "Cold Relief wins if they successfully escort 3+ supply convoys to civilian centers.",
        specialRules: "Arctic terrain: all units suffer cold weather penalties. Civilian convoy units must be protected as objectives in M2.",
        purchaseOptions: "Roll 2D6 after each track: 9+ = 1 Mech (Wasp/Stinger variant); 11+ = 1 from Federated Suns or Draconis Combine table.",
        side: "A",
      },
      {
        contractNumber: "712345B",
        name: "Reforged Honor",
        employer: "DCMS Occupation Authority",
        contractType: "GARRISON",
        terrain: "Tundra/Arctic",
        planet: "Xhosa VII",
        faction: "Draconis Combine",
        durationMonths: 3,
        basePayPct: 90, basePayStep: 6,
        supportType: "STRAIGHT", supportPct: 100, supportStep: 7,
        transportPct: 50, transportStep: 7,
        salvageRightsPct: 30, salvageStep: 6,
        commandRights: "HOUSE", commandStep: 7,
        commandNonNegotiable: false,
        intensity: "3 tracks, one per month",
        trackSequence: "Opposing contract to 712345A. Same Xhosa VII timeline.",
        victoryCondition: "Reforged Honor wins if they prevent more than 2 supply convoys from reaching civilian centers.",
        specialRules: "Arctic terrain rules. DCMS honor code: breaking certain conduct rules reduces reputation.",
        purchaseOptions: "Same tables as 712345A.",
        side: "B",
      },
    ],
  },

  {
    name: "Act of Piracy",
    planet: "Tancredi IV / De Berry",
    primaryTerrain: "Varied",
    faction: "Independent / Pirate",
    recommendedFor: "EXPERIENCED",
    scheduleType: "fixed",
    monthlySchedule: [
      { month: 1, tracks: [], note: "No tracks — travel to target system." },
      { month: 2, tracks: [{ trackType: "Objective Raid", attackerSide: "A", note: "Pirates raid civilian/military targets. Roll on Piracy Track Table for specific target and opposing force." }] },
      { month: 3, tracks: [], note: "No tracks — Pirates escape with loot; Anti-Piracy forces regroup." },
    ],
    contracts: [
      {
        contractNumber: "PIRACY-A",
        name: "Act of Piracy",
        employer: "Self (Pirate Operation)",
        contractType: "ACTS_OF_PIRACY",
        terrain: "Varied",
        planet: "Tancredi IV or De Berry",
        faction: "Independent",
        durationMonths: 3,
        basePayPct: 0, basePayStep: 1,
        supportType: "NONE", supportPct: 0, supportStep: 1,
        transportPct: 0, transportStep: 5,
        salvageRightsPct: 100, salvageStep: 13,
        commandRights: "INDEPENDENT", commandStep: 11,
        commandNonNegotiable: true,
        intensity: "1 track in Month 2",
        trackSequence: "M1: No tracks (travel). M2: Objective Raid — roll on Piracy Track Table for target system, loot type, opposing force, and conditions. M3: No tracks (escape).",
        victoryCondition: "Pirates win if they successfully complete the Objective Raid track.",
        specialRules: "Non-negotiable terms — no employer. Piracy income: fixed base payment per scale regardless of track result, plus roll on Piracy Component Table for each component pirated. Piracy Reputation check after contract: roll 2D6 vs 9+ (−2 if victorious). Failure = −1 Rep per 500 SP earned.",
        purchaseOptions: "Roll 2D6 each month: 7+ = 1 Mech; 11+ = 2. Sea Fox and Mercenary/Pirate tables.",
        side: "A",
      },
      {
        contractNumber: "PIRACY-B",
        name: "Anti-Piracy Garrison",
        employer: "Tancredi IV Planetary Militia",
        contractType: "GARRISON",
        terrain: "Varied",
        planet: "Tancredi IV or De Berry",
        faction: "Independent",
        durationMonths: 3,
        basePayPct: 100, basePayStep: 7,
        supportType: "STRAIGHT", supportPct: 80, supportStep: 6,
        transportPct: 50, transportStep: 7,
        salvageRightsPct: 50, salvageStep: 8,
        commandRights: "INDEPENDENT", commandStep: 11,
        commandNonNegotiable: false,
        intensity: "1 track in Month 2",
        trackSequence: "Opposing contract to PIRACY-A. Defend civilian targets against the pirate raid in Month 2.",
        victoryCondition: "Anti-Piracy Garrison wins if they prevent the pirates from completing the Objective Raid.",
        specialRules: "Same Piracy Reputation mechanics apply if garrison commits unauthorized actions.",
        purchaseOptions: "Mercenary/Pirate Purchase Options Table.",
        side: "B",
        optional: true,
      },
    ],
  },

  {
    name: "Game Worlds",
    planet: "Carcassonne / Xhosa VII / Tybalt",
    primaryTerrain: "Varied (Arena)",
    faction: "Independent",
    recommendedFor: "EXPERIENCED",
    scheduleType: "special",
    contracts: [
      {
        contractNumber: "DUEL-A",
        name: "Gladiatorial Circuit",
        employer: "None (Arena operator)",
        contractType: "RETAINER",
        terrain: "Varied (Arena)",
        planet: "Carcassonne, Xhosa VII, or Tybalt",
        faction: "Independent",
        durationMonths: 1,
        basePayPct: 0, basePayStep: 1,
        supportType: "NONE", supportPct: 0, supportStep: 1,
        transportPct: 0, transportStep: 1,
        salvageRightsPct: 0, salvageStep: 1,
        commandRights: "INDEPENDENT", commandStep: 11,
        commandNonNegotiable: true,
        intensity: "1–3 Duel tracks",
        trackSequence: "Game Worlds are solo arena duels — no opposing player required. Each game world has unique rules. Combat pay equals VP earned (1 VP = 1 SP). Choose game world: Carcassonne (fungal terrain, no class 6), Xhosa VII (Easter Ice Fights, blizzard conditions), or Tybalt (grudge matches at Festival Grounds, no class 5).",
        victoryCondition: "Defeat your opponent in a Duel track. Double reward if opponent is larger weight class.",
        specialRules: "This is NOT a standard opposing contract. Multiple players can each take this independently. Duel track only — 1 Mech vs 1 Mech by weight class. Scale 1 costs/payments regardless of force scale. Gladiator Generator tables in book for solo play opponent.",
        purchaseOptions: "N/A",
        side: "A",
        optional: true,
      },
    ],
  },

  {
    name: "Mallory's World",
    planet: "Mallory's World",
    primaryTerrain: "Savannah/Urban",
    faction: "Draconis Combine (Disputed with Federated Suns)",
    recommendedFor: "VETERAN_CAPSTONE",
    scheduleType: "special",
    contracts: [
      {
        contractNumber: "599157A",
        name: "Raise the Dragon Banner",
        employer: "Daimyo Kenshin Tadashi, Draconis Combine",
        contractType: "INVASION",
        terrain: "Savannah/Urban",
        planet: "Loneliness Island, Mallory's World",
        faction: "Draconis Combine",
        durationMonths: 5,
        basePayPct: 60, basePayStep: 3,
        supportType: "STRAIGHT", supportPct: 40, supportStep: 3,
        transportPct: 100, transportStep: 9,
        salvageRightsPct: 50, salvageStep: 8,
        commandRights: "LIAISON", commandStep: 8,
        commandNonNegotiable: true,
        intensity: "5–10 battle tracks over 5 months (hex map campaign)",
        trackSequence: "Hex map campaign on Loneliness Island. Scale 3 required. Base pay and maintenance paid bimonthly. Map turns = 2 weeks each. Multiple combat tracks per map turn possible. Formations (max 4, max 5 units each, must contain ≥1 Mech) move across hex map fighting for key hexes. Strategic Reinforcement: up to 4 Mechs replaced per contract.",
        victoryCondition: "Raise the Dragon Banner wins if they control the FABL facility hex and establish a durable military base on Loneliness Island by contract end.",
        specialRules: "Scale 3 required. Hex map campaign system — see book pp.135–142. Bimonthly pay. Formations with BSP. Key NPCs: Haqikah Antar (FABL/RSIS), Gulnam Koban (BPWW), Xander Fenetry (LINGO), Clyde Hideyoshi-Ellsworth (Boshi-gumi). Writ of nobility possible for Fed Suns victor.",
        purchaseOptions: "Draconis Combine Purchase Options Table. Certain hexes must be held to purchase units.",
        side: "A",
      },
      {
        contractNumber: "599157B",
        name: "Raise the Sword and Sunburst",
        employer: "Baroness Colleen Sandoval, Federated Suns",
        contractType: "INVASION",
        terrain: "Savannah/Urban",
        planet: "Loneliness Island, Mallory's World",
        faction: "Federated Suns",
        durationMonths: 5,
        basePayPct: 60, basePayStep: 3,
        supportType: "STRAIGHT", supportPct: 40, supportStep: 3,
        transportPct: 100, transportStep: 9,
        salvageRightsPct: 50, salvageStep: 8,
        commandRights: "LIAISON", commandStep: 8,
        commandNonNegotiable: true,
        intensity: "5–10 battle tracks over 5 months (hex map campaign)",
        trackSequence: "Opposing contract to 599157A. Same Loneliness Island hex map. Sandoval insurgent force contests DC control.",
        victoryCondition: "Sword and Sunburst wins if they prevent Dragon Banner from controlling the FABL facility, or establish their own military base and hold it at contract end. Writ of nobility (Loneliness Island fiefdom) awarded if holding a base upon DCMS eviction.",
        specialRules: "Scale 3 required. Same hex map rules as 599157A. Same NPC interactions. Baroness offers lesser payment for forcing enemy mercenary force to withdraw even without holding the island.",
        purchaseOptions: "Federated Suns Purchase Options Table. Certain hexes must be held to purchase units.",
        side: "B",
      },
    ],
  },
];

export function getHotSpotByName(name: string): HotSpotData | undefined {
  return HOT_SPOTS_DATA.find((hs) => hs.name === name);
}

export function getContractTemplate(hotSpot: string, side: "A" | "B"): ContractTemplate | undefined {
  const hs = getHotSpotByName(hotSpot);
  return hs?.contracts.find((c) => c.side === side);
}

export function getAllContractTemplates(): ContractTemplate[] {
  return HOT_SPOTS_DATA.flatMap((hs) => hs.contracts);
}
